{% set name = "libertem-qd-mpx" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libertem_qd_mpx-{{ version }}.tar.gz
  sha256: 6d7266a203b34b7e3f10be72da0a7d39e5e0f7c8064981b50e81061d965386ae

build:
  skip: true  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }} >=1.66
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.5,<2.0
    - numpy
    - pip
  run:
    - python
    - opentelemetry-api

test:
  commands:
    - pip check
  imports:
    - libertem_qd_mpx
  requires:
    - pip

about:
  home: https://github.com/LiberTEM/LiberTEM-rs/
  summary: LiberTEM support for Quantum Dectectors Merlin detectors
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    Python package for efficiently receiving data
    from Quantum Detectors Merlin detectors

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
